In [1]:
# Imported libraries
import numpy as np
import pandas as pd

In [4]:
# DataFrame 
df = pd.read_csv('../datos/features_with_meta.csv')
df.head()

,spo2_mean,spo2_std,spo2_var,spo2_mode,spo2_min,spo2_max,airflow_mean,airflow_median,airflow_std,airflow_mean_PSD_0_0.1,...,skewness_rr,hrv_total_power,hrv_lf_power,hrv_hf_power,hrv_lf_hf_ratio,hrv_shannon_entropy,label,subject,Age,Sex
0,96.701000,1.695563,2.874932,98.0,93.0,98.0,0.030024,0.057825,0.184668,0.041587,...,0.070594,0.004022,0.001222,0.000953,1.282583,2.385949,N,a01,51,M
1,97.350000,0.678602,0.460500,98.0,96.0,98.0,0.022421,0.026675,0.138686,0.020508,...,-0.418282,0.002435,0.000894,0.000721,1.238604,2.707965,N,a01,51,M
2,98.368667,0.773575,0.598418,99.0,97.0,100.0,0.037414,0.113125,0.324112,0.235710,...,0.088838,0.005727,0.001135,0.001101,1.030521,2.332296,N,a01,51,M
3,99.000000,0.000000,0.000000,99.0,99.0,99.0,0.002367,0.009575,0.261016,0.106126,...,-0.652262,0.003871,0.000959,0.000322,2.982284,2.037821,N,a01,51,M
4,98.132833,0.426054,0.181522,98.0,97.0,99.0,0.020547,0.058950,0.175053,0.076721,...,0.276769,0.002300,0.001328,0.000298,4.459743,2.444649,N,a01,51,M

## **<span style="color:#1a73e8;">Data Frame info</span>**

In [10]:
# --- DataFrame info ---
print("=== DataFrame Info ===")
df.info()

=== DataFrame Info ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3898 entries, 0 to 3897
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   spo2_mean                 3898 non-null   float64
 1   spo2_std                  3898 non-null   float64
 2   spo2_var                  3898 non-null   float64
 3   spo2_mode                 3898 non-null   float64
 4   spo2_min                  3898 non-null   float64
 5   spo2_max                  3898 non-null   float64
 6   airflow_mean              3897 non-null   float64
 7   airflow_median            3897 non-null   float64
 8   airflow_std               3897 non-null   float64
 9   airflow_mean_PSD_0_0.1    3897 non-null   float64
 10  airflow_mean_PSD_0.4_0.5  3897 non-null   float64
 11  mean_rr                   3895 non-null   float64
 12  median_rr                 3895 non-null   float64
 13  var_rr                    3888 non-null   float64
 14  rmssd                     3888 non-null   float64
 15  std_rr                    3888 non-null   float64
 16  var_rr_ratio              3881 non-null   float64
 17  kurtosis_rr               3878 non-null   float64
 18  skewness_rr               3881 non-null   float64
 19  hrv_total_power           3878 non-null   float64
 20  hrv_lf_power              3878 non-null   float64
 21  hrv_hf_power              3878 non-null   float64
 22  hrv_lf_hf_ratio           3878 non-null   float64
 23  hrv_shannon_entropy       3878 non-null   float64
 24  label                     3898 non-null   object
 25  subject                   3898 non-null   object
 26  Age                       3898 non-null   int64
 27  Sex                       3898 non-null   object
dtypes: float64(24), int64(1), object(3)
memory usage: 852.8+ KB

In [11]:
# --- Null values per column ---
print("\n=== Null Values per Column ===")
print(df.isnull().sum())

=== Null Values per Column ===
spo2_mean                    0
spo2_std                     0
spo2_var                     0
spo2_mode                    0
spo2_min                     0
spo2_max                     0
airflow_mean                 1
airflow_median               1
airflow_std                  1
airflow_mean_PSD_0_0.1       1
airflow_mean_PSD_0.4_0.5     1
mean_rr                      3
median_rr                    3
var_rr                      10
rmssd                       10
std_rr                      10
var_rr_ratio                17
kurtosis_rr                 20
skewness_rr                 17
hrv_total_power             20
hrv_lf_power                20
hrv_hf_power                20
hrv_lf_hf_ratio             20
hrv_shannon_entropy         20
label                        0
subject                      0
Age                          0
Sex                          0
dtype: int64

In [9]:
# --- Descriptive statistics (excluding some columns) ---
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

exclude_cols = ["label", "Sex", "subject"]  # columnas a excluir
print("\n=== Descriptive Statistics (excluding selected columns) ===")
display(df.drop(columns=exclude_cols).describe())

=== Descriptive Statistics (excluding selected columns) ===

,spo2_mean,spo2_std,spo2_var,spo2_mode,spo2_min,spo2_max,airflow_mean,airflow_median,airflow_std,airflow_mean_PSD_0_0.1,airflow_mean_PSD_0.4_0.5,mean_rr,median_rr,var_rr,rmssd,std_rr,var_rr_ratio,kurtosis_rr,skewness_rr,hrv_total_power,hrv_lf_power,hrv_hf_power,hrv_lf_hf_ratio,hrv_shannon_entropy,Age
count,3898.000000,3898.000000,3898.000000,3898.000000,3898.000000,3898.000000,3897.000000,3897.000000,3897.000000,3897.000000,3897.000000,3895.000000,3895.000000,3888.000000,3888.000000,3888.000000,3881.000000,3878.000000,3881.000000,3878.000000,3878.000000,3878.000000,3878.000000,3878.000000,3898.000000
mean,90.673924,3.609467,43.816697,91.665726,83.757568,95.772191,-0.000079,0.008052,0.205869,0.035400,0.037644,1.007524,0.968380,0.411663,0.202580,0.180577,0.155753,3.241680,0.566617,0.259645,0.052335,0.016633,2.959742,2.252458,43.345818
std,8.003352,5.549446,181.030648,10.432739,18.065529,2.968646,0.049016,0.100144,0.093263,0.043219,0.064296,0.593328,0.508954,8.378773,0.944554,0.615754,2.232655,8.833211,1.668435,3.840789,0.621893,0.130878,4.868152,0.570195,7.808456
min,0.868667,0.000000,0.000000,0.000000,0.000000,73.000000,-0.146342,-0.192750,0.044301,0.000394,0.000000,0.561667,0.525000,0.000025,0.007022,0.005000,0.000077,-1.729269,-6.426924,0.000032,0.000000,0.000003,0.000000,0.102806,31.000000
25%,88.539000,0.465438,0.216633,92.000000,78.000000,95.000000,-0.044543,-0.083100,0.128043,0.005415,0.005818,0.888346,0.840000,0.003226,0.034400,0.056801,0.001252,-0.600294,-0.243205,0.002294,0.000415,0.000182,0.769750,1.799111,38.000000
50%,94.106583,0.906393,0.821550,95.000000,92.000000,96.000000,-0.021559,-0.007325,0.197324,0.018338,0.014078,0.965082,0.950000,0.008995,0.066769,0.094840,0.004290,-0.013425,0.241646,0.007467,0.001498,0.000806,1.656450,2.321901,44.000000
75%,95.383667,5.704944,32.546392,96.000000,95.000000,97.000000,0.042549,0.089300,0.263943,0.051894,0.037314,1.047895,1.040000,0.025721,0.139948,0.160377,0.018770,2.017785,0.986065,0.021007,0.004970,0.002996,3.572465,2.639976,52.000000
max,99.000000,47.556193,2261.591453,99.000000,99.000000,100.000000,0.159641,0.294750,0.679454,0.434127,0.617125,26.875000,26.875000,369.568689,35.130000,19.224169,108.705687,73.487668,8.586069,164.824451,19.847840,5.165253,192.021985,3.837433,54.000000